### PR TITLE
Fix #39

### LINKED ISSUE #39: ContentValues retrieved before beforeCreate is invoked
`Model.save` retrieves all `ContentValues` before invoking `beforeCreate()` which breaks fields that are not nullable but are initialized in `beforeCreate()`. An example of this can be seen in the sample where a Note cannot be saved because of a `NullPointerException` thrown by the `DateSerializer` for the field `createdAt`.

### PR DESCRIPTION
**Pull request by zsiegel**
ensures beforeCreate() is called before content values are grabbed

### CODE REVIEW

**Comment by emilsjolander** [comment]
Awesome! I'd like it if you added a test case for this so we don't have any regressions. There are a couple of test in the ModelTest class which test that callbacks are called, add something there.

**Comment by zsiegel** [comment]
OK. I will take a look and add some tests.

Zachary Siegel
zsiegel87@gmail.com

**Comment by zsiegel** [comment]
Go ahead and take a look. I think I covered what we are trying to guard against here. I took the broken sample example from the Notes class.

**Comment by emilsjolander** [comment]
instead of checking if m.createdAt is not null (this was never a problem), check so that the "created_at" value in the content values is non-null

**Comment by zsiegel** [comment]
Yes thats right! Good catch thanks!

**Comment by emilsjolander** [comment]
Great work! i'll make a release now, should be in maven central sometime in the next couple of hours

**Comment by datadanne** [comment]
Nice work!

**Pull request merged**
