### PR TITLE
Add @Unique annotation

### PR DESCRIPTION
**Pull request by MariusVolkhart**
This annotation will specify that a column is to be unique and as such
can be used as a candidate key. As written, this annotation can be
combined with any other annotations.

There is a provided test which fails as written since it relies on an
actual database.

The annotation can be used as follows:

``` java
public class MyModel extends Model {
    @Unique
    private String name;

    @Unique(ConflictClause.FAIL)
    private String email;
}
```

### CODE REVIEW

**Comment by MariusVolkhart** [comment]
An alternative name for the `ConflictClause` is `OnConflict`, since that's the type of clause, and it reads more fluently. For example:

``` java
public class MyModel extends Model {
    @Unique
    private String name;

    @Unique(OnConflict.FAIL)
    private String email;
}
```

 I'd like input on which naming style is preferred.

**Comment by emilsjolander** [comment]
I will look into this and your other pull request in more detail this weekend (after my exams :+1:). I would however want to quickly point out that it seems like you are using spaces to indent and the project is currently using tabs. This makes for a very confusing diff so i would appreciate it if you changed to use tabs for this project. (I don't have a strong opinion in the tabs vs spaces war but as the project currently uses tabs i think we should continue on that path) Thanks!

**Comment by MariusVolkhart** [comment]
Oh I missed the tabs. Will go change that. Good luck and thanks for responding and letting me know!

**Comment by emilsjolander** [comment]
Awesome work!

**Pull request merged**
