### PR TITLE
Unique combinations

### PR DESCRIPTION
**Pull request by mechinn**

### CODE REVIEW

**Comment by emilsjolander** [comment]
Firstly:
- Tests
- Readme

Secondly, i don't really like having a `@Unique` and a `@UniqueCombo` annotation. I have been thinking about this for a couple of days and i think a good solution would be that the `@Unique` annotation accepts a `groupId` (not sure of the name) parameter. All `@Unique` columns with the same `groupId` will be a unique combo.

What do you think of this solution?

**Comment by mechinn** [comment]
1: Oops, didn't even think about unit tests...
2: Sure once we settle on an API
3: Interesting idea and I like it, we could just do a simple optional parameter of an int or something and on the sprinkles side do a unique table constraint on those with the same integer ID instead of a unique column, even if the user only puts 1 @Unique with that ID you can have unique table constraints for 1 column and it acts the same as a unique column (though idk the performance difference if there is any)

**Comment by edu-zamora** [comment]
@emilsjolander, @mechinn: Another alternative would be to be able to add a @Unique annotation to the class (like the @Table annotation) that accepts strings representing the name of the columns.

It seems more clear to me:
- constraints specific to one column are applied with an annotation to its corresponding field
- constraints to the table are applied with an annotation to the class

**Comment by emilsjolander** [comment]
@edu-zamora while i do like the thought behind this a lot of annotations can be thought of as being "owned" by the table and not the column (is a column a primary key or does the table have a primary key ?). I like the idea of being able to look at a property (column) and being able to see what restrictions are put on it, having a unique combination does make this harder but i still think the correct solution is to have the annotation on the column. Another pro with this is that it is fully backwards compatible with the current `@Unique` annotation.

@mechinn I'm not sure if a integer or string "group id" is best. Having a string would make for a more readable unique constraint.

``` java
@Table("Persons")
class Person {
    //... stuff

    @Column("first_name")
    @Unique(group = "name")
    String firstName;

    @Column("last_name")
    @Unique(group = "name")
    String lastName;
}
```

**Comment by edu-zamora** [comment]
@emilsjolander As I see it, constraints that apply to just one column would translate to an annotation to the corresponding field. Constraints that apply to no column or to more than one column, would translate to an annotation to the class.

I do like the nice side-effect of being able to see all the constraints related to a column in just one place (the field definition), though.

In any case, I will be happy as long as this is supported and it is readable and understandable for users, with minimal documentation.

In case we go for the last suggestion (@Unique constraint on fields, with grouping option):
- I vote for string over id
- Would @Unique(), without grouping, still be supported?
- Would just one @Unique(group = "name") be supported (equivalent to @Unique() then)?

**Comment by emilsjolander** [comment]
yeah i would think that just a single `@Unique(group = "name")` should be supported and be equivalent to leaving the group name out

**Comment by edu-zamora** [comment]
Sounds good!

**Comment by emilsjolander** [comment]
@mechinn want any help with this or you think you got it ?:)

**Comment by mechinn** [comment]
I've got it :) I'll change the unique api to what you guys came up with as
soon as I get a chance

**Comment by emilsjolander** [comment]
Awesome! Looking forward to it :+1:

**Comment by emilsjolander** [comment]
@mechinn any update?

**Comment by mechinn** [comment]
:( between being sick and buried again nope not yet... hang on, i'll get to
it unless one of you guys want to get it done sooner

**Comment by emilsjolander** [comment]
No problem, I was informed yesterday of a big bug in the migration system which needs it to be overhauled. I am currently looking into a couple of ways of solving it and some of them would change how contraints on columns are managed. So maybe hold of on this for a couple of days

**Comment by mechinn** [comment]
oh :( im actually done other than making sure that unit tests work

**Comment by mechinn** [comment]
well i know you said you have a big fix ahead so if you want me to merge this with that later i can but there you go

**Comment by emilsjolander** [comment]
Thanks you for your hard work! Big changes will be coming tomorrow but i will make sure to integrate this :+1:

**Comment by mechinn** [comment]
Hahaha no prob, there really weren't that many lines of code

**Pull request merged**
