### PR TITLE
reuse callbacks, default table/column names, & unique combinations

### PR DESCRIPTION
**Pull request by mechinn**
The library is great but to integrate it into a project I am working on I needed to add unique combinations and that I could restart the loaders to working with callbacks more than once.

While adding that I made it so that I could use the variable names and class names as the column names and table names respectively by default if no argument is given to @column or @table

I hope that you and the rest of your library's users find these modifications useful

### CODE REVIEW

**Comment by emilsjolander** [comment]
I would appreciate it if this were three separate pull requests as the changes aren't dependant on each other, this makes it easier to merge one change while discussing and changing parts of another.

Regarding the changes.
- Having implicit table/column names has been proposed before and i state the reasons for not wanting this in pull request #35.
- Changing `initLoader()` -> `restartLoader()` seems like a valid change. Split it into a seperate pull request and i'll merge it :+1: 
- Unique combinations should definitely be added. I am not so sure about the proposed Api but open a specific pull request for this feature and we can discuss it there.

**Comment by emilsjolander** [comment]
@mechinn any update?

**Comment by mechinn** [comment]
Sorry! Ive been rushing to get a project done before a deadline. I'll try and fix up the pull request within a week

**Comment by emilsjolander** [comment]
awesome :)

**Comment by mechinn** [comment]
Sorry that took so long to put up, finally finished the major feature of the other project I am working on :D

**Comment by emilsjolander** [comment]
No problem! Just happy to see the pull requests :+1:

**Comment by mechinn** [comment]
NP, this library is awesome! Great work with it and I'm glad to help :)

**Pull request closed without merging**
