### PR TITLE
Let the user choose a database name + Change numbering for DB Versions.

### PR DESCRIPTION
**Pull request by fstephany**
The version number for a DB was based on the number of migrations. When you want to open an existing Database, you don't want to apply a migration, just open the DB. As the SQLiteOpenHelper starts to version at 1 and not 0, we increment the number of migrations by one.

### CODE REVIEW

**Comment by fstephany** [comment]
@emilsjolander Hopefuly, I didn't break anything ;)

**Comment by jdreesen** [comment]
I don't think this will work if you use an existing database with a version > 1 and your migration count is lower than the existing database's version number. In this case `DbOpenHelper` will call `onDowngrade()` which throws a `SQLiteException` by default. To avoid this it should be possible to set a base version which should be the current database's version number.

**Comment by emilsjolander** [comment]
how about an `initWithExistingDatabase(Context c, String name, int version)` ?

**Comment by fstephany** [comment]
As I see it, there's actually two different use cases:
1. An deployed app with an existing DB (and thus an existing name)
2. An app with an external DB in assets that you want to use (using sqlite-asset-helper for example)

In 1, you probably want to be able to integrate the Migration system from Sprinkles.
 in 2, the migration should be handled by sqlite-asset-helper.

**Comment by emilsjolander** [comment]
Lets start solving for the problem with an existing DB (1). I would think this is the most usual problem by far.

**Comment by emilsjolander** [comment]
What to you think @fstephany ? will you be updating this pull request?

**Comment by fstephany** [comment]
Sounds great. I'll update this pull request.

**Comment by zsiegel** [comment]
Any update on this? I could actually use this in my current project?

**Comment by fstephany** [comment]
I've removed the `SQLDatabase getInstance()` from the DbOpenHelper. It is now held by the Sprinkles singleton.

I've pushed the change to my master branch. There is something wrong in my Git workflow. I should learn more about stashing/rebasing at some point...

**Comment by emilsjolander** [comment]
No worries, i will change that myself. Thanks for the addition!

**Comment by hak-ziadov** [comment]
Hi, please could you put an example of using sprinkles with an external DB in assets ( using sqlite-asset-helper ) 
Thanks in advance

**Comment by fixmycode** [comment]
Is there any examples available on how to use an existing database with asset helper? please? @fstephany

**Pull request merged**
